name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.10']

    steps:
      - uses: compas-dev/compas-actions.build@v3
        with:
          python: ${{ matrix.python }}
          use_conda: true
          invoke_lint: false

      - name: Verify imports
        shell: bash -l {0}
        run: |
          python -c "import compas; print(compas.__version__)"
          python -c "import compas_fab; print(compas_fab.__version__)"
          python -c "import compas_slicer; print(compas_slicer.__version__)"
          python -c "import compas_rrc; print(compas_rrc.__version__)"
          python -m compas
